name: Build and Deploy on Azure VM

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Azure VM
        env:
          AZURE_VM_IP: ${{ secrets.AZURE_VM_IP }}
          GITHUB_PAT: ${{ secrets.PRIVATE_ACCESS_TOKEN }}
        run: |
          # Install SSH and set up SSH key
          mkdir -p ~/.ssh
          echo "${{ secrets.AZURE_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          
          # SSH into Azure VM and perform deployment
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa azureuser@$AZURE_VM_IP << EOF
            

            # Remove existing repositories
            rm -rf FestQuestFrontend
            rm -rf FestQuestBackend

            # Clone repositories using PAT
            git clone https://${GITHUB_PAT}@github.com/sgtasswipe/FestQuestFrontend
            git clone https://${GITHUB_PAT}@github.com/sgtasswipe/FestQuestBackend

            # Backend Deployment
            cd FestQuestBackend
            docker build -t festquest-backend:latest .
            docker stop festquest-backend || true
            docker rm festquest-backend || true
            docker run -d --name festquest-backend -p 8080:8080 festquest-backend:latest

            # Frontend Deployment
            cd ../FestQuestFrontend/src/docker
            docker build -t festquest-frontend:latest .
            docker stop festquest-frontend || true
            docker rm festquest-frontend || true
            docker run -d --name festquest-frontend -p 80:80 festquest-frontend:latest
          EOF